export const homeDataConstants = {
	
	
	DATA_GET_REQUEST: "DATA_GET_REQUEST",
	DATA_GET_FAILURE: "DATA_GET_FAILURE",
	DATA_GET_SUCCESS: "DATA_GET_SUCCESS",

	
	SHOW_ADD_MENU_MODAL: "SHOW_ADD_MENU_MODAL",
	HIDE_ADD_MENU_MODAL: "HIDE_ADD_MENU_MODAL",

	GET_QR_REQUEST: "GET_QR_REQUEST",
	GET_QR_SUCCESS: "GET_QR_SUCCESS",
	GET_QR_FAILURE: "GET_QR_FAILURE",
	
	DATA_TOUR_POINTS_GET_REQUEST: "DATA_TOUR_POINTS_GET_REQUEST",
	DATA_TOUR_POINTS_GET_FAILURE: "DATA_TOUR_POINTS_GET_FAILURE",
	DATA_TOUR_POINTS_GET_SUCCESS: "DATA_TOUR_POINTS_GET_SUCCESS",

	
	PREVIOUS_DATA_GET_REQUEST: "PREVIOUS_DATA_GET_REQUEST",
	PREVIOUS_DATA_GET_FAILURE: "PREVIOUS_DATA_GET_FAILURE",
	PREVIOUS_DATA_GET_SUCCESS: "PREVIOUS_DATA_GET_SUCCESS",

	
	TOUR_SUBMIT_REQUEST: "TOUR_SUBMIT_REQUEST",
	TOUR_SUBMIT_SUCCESS: "TOUR_SUBMIT_SUCCESS",
	TOUR_SUBMIT_FAILURE: "TOUR_SUBMIT_FAILURE",

	
	TOUR_UPDATE_REQUEST: "TOUR_UPDATE_REQUEST",
	TOUR_UPDATE_SUCCESS: "TOUR_UPDATE_SUCCESS",
	TOUR_UPDATE_FAILURE: "TOUR_UPDATE_FAILURE",

	
	POI_UPDATE_REQUEST: "POI_UPDATE_REQUEST",
	POI_UPDATE_SUCCESS: "POI_UPDATE_SUCCESS",
	POI_UPDATE_FAILURE: "POI_UPDATE_FAILURE",

	HIDE_ADD_MODAL: "HIDE_ADD_MODAL",
	SHOW_ADD_MODAL: "SHOW_ADD_MODAL",
	
	HIDE_MODAL: "HIDE_MODAL",
	SHOW_MODAL: "SHOW_MODAL",
	
	SUCCESS_MODAL_SHOW: "SUCCESS_MODAL_SHOW",
	SUCCESS_MODAL_HIDE: "SUCCESS_MODAL_HIDE",

	
	FAILURE_MODAL_SHOW: "FAILURE_MODAL_SHOW",
	FAILURE_MODAL_HIDE: "FAILURE_MODAL_HIDE",

	
	UPDATE_MENU_PHOTO_SUCCESS: "UPDATE_MENU_PHOTO_SUCCESS",
	UPDATE_MENU_PHOTO_FAILURE: "UPDATE_MENU_PHOTO_FAILURE",

	HIDE_SUCCESS_FAILURE_MODAL: "HIDE_SUCCESS_FAILURE_MODAL",
};
