export const homeDataConstants = {
	
	
	DATA_GET_REQUEST: "DATA_GET_REQUEST",
	DATA_GET_FAILURE: "DATA_GET_FAILURE",
	DATA_GET_SUCCESS: "DATA_GET_SUCCESS",

	
	PREVIOUS_DATA_GET_REQUEST: "PREVIOUS_DATA_GET_REQUEST",
	PREVIOUS_DATA_GET_FAILURE: "PREVIOUS_DATA_GET_FAILURE",
	PREVIOUS_DATA_GET_SUCCESS: "PREVIOUS_DATA_GET_SUCCESS",

	
	HIDE_MODAL: "HIDE_MODAL",
	SHOW_MODAL: "SHOW_MODAL",
	
};
