export const homeDataConstants = {
	
	
	DATA_GET_REQUEST: "DATA_GET_REQUEST",
	DATA_GET_FAILURE: "DATA_GET_FAILURE",
	DATA_GET_SUCCESS: "DATA_GET_SUCCESS",

	
	PREVIOUS_DATA_GET_REQUEST: "PREVIOUS_DATA_GET_REQUEST",
	PREVIOUS_DATA_GET_FAILURE: "PREVIOUS_DATA_GET_FAILURE",
	PREVIOUS_DATA_GET_SUCCESS: "PREVIOUS_DATA_GET_SUCCESS",

	
	TOUR_SUBMIT_REQUEST: "TOUR_SUBMIT_REQUEST",
	TOUR_SUBMIT_SUCCESS: "TOUR_SUBMIT_SUCCESS",
	TOUR_SUBMIT_FAILURE: "TOUR_SUBMIT_FAILURE",

	
	TOUR_UPDATE_REQUEST: "TOUR_UPDATE_REQUEST",
	TOUR_UPDATE_SUCCESS: "TOUR_UPDATE_SUCCESS",
	TOUR_UPDATE_FAILURE: "TOUR_UPDATE_FAILURE",

	HIDE_ADD_MODAL: "HIDE_ADD_MODAL",
	SHOW_ADD_MODAL: "SHOW_ADD_MODAL",
	
	HIDE_MODAL: "HIDE_MODAL",
	SHOW_MODAL: "SHOW_MODAL",
	
};
