export const reportConstants = {
	
	REPORT_GET_REQUEST: "REPORT_GET_REQUEST",
	REPORT_GET_FAILURE: "REPORT_GET_FAILURE",
	REPORT_GET_SUCCESS: "REPORT_GET_SUCCESS",

	
	PREVIOUS_REPORT_GET_REQUEST: "PREVIOUS_REPORT_GET_REQUEST",
	PREVIOUS_REPORT_GET_FAILURE: "PREVIOUS_REPORT_GET_FAILURE",
	PREVIOUS_REPORT_GET_SUCCESS: "PREVIOUS_REPORT_GET_SUCCESS",
	
	HIDE_ADD_MENU_MODAL: "HIDE_ADD_MENU_MODAL",
	SHOW_ADD_MENU_MODAL: "SHOW_ADD_MENU_MODAL",

	MENU_SUBMIT_SUCCESS: "MENU_SUBMIT_SUCCESS",
	MENU_SUBMIT_FAILURE: "MENU_SUBMIT_FAILURE",

	
	GET_MENU_SUCCESS: "GET_MENU_SUCCESS",
	GET_MENU_FAILURE: "GET_MENU_FAILURE"
};
