export const userConstants = {
	
	LOGIN_REQUEST: "LOGIN_REQUEST",
	LOGIN_SUCCESS: "LOGIN_SUCCESS",
	LOGIN_FAILURE: "LOGIN_FAILURE",

	ROLES_GET_REQUEST: "ROLES_GET_REQUEST",
	ROLES_GET_FAILURE: "ROLES_GET_FAILURE",
	ROLES_GET_SUCCESS: "ROLES_GET_SUCCESS",

	
	REGISTRATION_MAIL_REQUEST: "REGISTRATION_MAIL_REQUEST",
	REGISTRATION_MAIL_SUCCESS: "REGISTRATION_MAIL_SUCCESS",
	REGISTRATION_MAIL_FAILURE: "REGISTRATION_MAIL_FAILURE"
	
};
