export const userConstants = {
	
	LOGIN_REQUEST: "LOGIN_REQUEST",
	LOGIN_SUCCESS: "LOGIN_SUCCESS",
	LOGIN_FAILURE: "LOGIN_FAILURE",

	ROLES_GET_REQUEST: "ROLES_GET_REQUEST",
	ROLES_GET_FAILURE: "ROLES_GET_FAILURE",
	ROLES_GET_SUCCESS: "ROLES_GET_SUCCESS",
	
};
